name: gradle.build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD: ${{ github.run_number }}
      SHA: ${{ github.sha }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Fix wrapper permissions
        run: chmod +x ./gradlew

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Prepare workspace
        run: ./gradlew --no-daemon classes

      - name: Build forge mod
        run: ./gradlew --build-cache build

      - name: Rename built forge mod
        run: mv build/libs/RendogClient-*.jar RendogClient-${{ github.run_number }}.jar

      - name: Generate forge mod checksum
        uses: ToxicAven/generate-checksum-file@v1
        with:
          filePath: RendogClient-${{ github.run_number }}.jar
          saveFile: RendogClient-${{ github.run_number }}-SHA256.txt
          algorithm: SHA256

      - name: Archive forge mod
        uses: actions/upload-artifact@v2
        with:
          name: RendogClient-${{ github.run_number }}
          path: RendogClient-${{ github.run_number }}.jar

      - name: Archive forge mod checksum
        uses: actions/upload-artifact@v2
        with:
          name: RendogClient-${{ github.run_number }}-SHA256.txt
          path: RendogClient-${{ github.run_number }}-SHA256.txt

      - name: Build plugin API
        run: ./gradlew apiJar --no-build-cache

      - name: Rename built plugin API
        run: mv build/libs/RendogClient-*-api.jar RendogClient-${{ github.run_number }}-api.jar

      - name: Generate API mod checksum
        uses: ToxicAven/generate-checksum-file@v1
        with:
          filePath: RendogClient-${{ github.run_number }}-api.jar
          saveFile: RendogClient-${{ github.run_number }}-api-SHA256.txt
          algorithm: SHA256

      - name: Archive plugin API
        uses: actions/upload-artifact@v2
        with:
          name: RendogClient-${{ github.run_number }}-api
          path: RendogClient-${{ github.run_number }}-api.jar

      - name: Upload API checksum
        uses: actions/upload-artifact@v2
        with:
          name: RendogClient-${{ github.run_number }}-api-SHA256.txt
          path: RendogClient-${{ github.run_number }}-api-SHA256.txt

      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
